set syndb(lsearch,lsearch,type) "TCLCMD"
set syndb(lsearch,lsearch,hint) "lsearch ?options? list pattern "
set syndb(lsearch,lsearch,arglist) [list -all -ascii -decreasing -dictionary -exact -glob -increasing -inline -integer -not -real -regexp -sorted -start]
set syndb(lsearch,-all,type) "TCLARG"
set syndb(lsearch,-all,hint)  ""
set syndb(lsearch,-all,arglist)  [list] 
set syndb(lsearch,-ascii,type) "TCLARG"
set syndb(lsearch,-ascii,hint)  ""
set syndb(lsearch,-ascii,arglist)  [list] 
set syndb(lsearch,-decreasing,type) "TCLARG"
set syndb(lsearch,-decreasing,hint)  ""
set syndb(lsearch,-decreasing,arglist)  [list] 
set syndb(lsearch,-dictionary,type) "TCLARG"
set syndb(lsearch,-dictionary,hint)  ""
set syndb(lsearch,-dictionary,arglist)  [list] 
set syndb(lsearch,-exact,type) "TCLARG"
set syndb(lsearch,-exact,hint)  ""
set syndb(lsearch,-exact,arglist)  [list] 
set syndb(lsearch,-glob,type) "TCLARG"
set syndb(lsearch,-glob,hint)  ""
set syndb(lsearch,-glob,arglist)  [list] 
set syndb(lsearch,-increasing,type) "TCLARG"
set syndb(lsearch,-increasing,hint)  ""
set syndb(lsearch,-increasing,arglist)  [list] 
set syndb(lsearch,-inline,type) "TCLARG"
set syndb(lsearch,-inline,hint)  ""
set syndb(lsearch,-inline,arglist)  [list] 
set syndb(lsearch,-integer,type) "TCLARG"
set syndb(lsearch,-integer,hint)  ""
set syndb(lsearch,-integer,arglist)  [list] 
set syndb(lsearch,-not,type) "TCLARG"
set syndb(lsearch,-not,hint)  ""
set syndb(lsearch,-not,arglist)  [list] 
set syndb(lsearch,-real,type) "TCLARG"
set syndb(lsearch,-real,hint)  ""
set syndb(lsearch,-real,arglist)  [list] 
set syndb(lsearch,-regexp,type) "TCLARG"
set syndb(lsearch,-regexp,hint)  ""
set syndb(lsearch,-regexp,arglist)  [list] 
set syndb(lsearch,-sorted,type) "TCLARG"
set syndb(lsearch,-sorted,hint)  ""
set syndb(lsearch,-sorted,arglist)  [list] 
set syndb(lsearch,-start,type) "TCLARG"
set syndb(lsearch,-start,hint)  ""
set syndb(lsearch,-start,arglist)  [list] 
