set syndb(resource,resource,type) "TCLCMD"
set syndb(resource,resource,hint) ""
set syndb(resource,resource,arglist) [list close delete files list open read types write]
set syndb(resource,close,type) "TCLARG"
set syndb(resource,close,hint)  ""
set syndb(resource,close,arglist)  [list] 
set syndb(resource,delete,type) "TCLARG"
set syndb(resource,delete,hint)  ""
set syndb(resource,delete,arglist)  [list] 
set syndb(resource,files,type) "TCLARG"
set syndb(resource,files,hint)  ""
set syndb(resource,files,arglist)  [list] 
set syndb(resource,list,type) "TCLARG"
set syndb(resource,list,hint)  ""
set syndb(resource,list,arglist)  [list] 
set syndb(resource,open,type) "TCLARG"
set syndb(resource,open,hint)  ""
set syndb(resource,open,arglist)  [list] 
set syndb(resource,read,type) "TCLARG"
set syndb(resource,read,hint)  ""
set syndb(resource,read,arglist)  [list] 
set syndb(resource,types,type) "TCLARG"
set syndb(resource,types,hint)  ""
set syndb(resource,types,arglist)  [list] 
set syndb(resource,write,type) "TCLARG"
set syndb(resource,write,hint)  ""
set syndb(resource,write,arglist)  [list] 
