namespace eval :: {
	# New
	::msgcat::mcset en_us "All Projects" "All Projects"

	# New
	::msgcat::mcset en_us "%s already exists! Please change the project name." "%s already exists! Please change the project name."
	# New
	::msgcat::mcset en_us "%s Updates" "%s Updates"
	# New
	::msgcat::mcset en_us "'%s' already exists, would you like to replace the existing file?" "'%s' already exists, would you like to replace the existing file?"
	# New
	::msgcat::mcset en_us "'%s' has been delete from the file system. Save it?" "'%s' has been delete from the file system. Save it?"
	# New
	::msgcat::mcset en_us "'%s' has been modified. Reload file ?" "'%s' has been modified. Reload file ?"
	# New
	::msgcat::mcset en_us "'%s' occurrence(s) were found." "'%s' occurrence(s) were found."
	# New
	::msgcat::mcset en_us "'%s' occurrence(s) were replaced." "'%s' occurrence(s) were replaced."
	# New
	::msgcat::mcset en_us "About" "About"
	# New
	::msgcat::mcset en_us "About..." "About..."
	# New
	::msgcat::mcset en_us "Active Project" "Active Project"
	# New
	::msgcat::mcset en_us "Add Block Comment" "Add Block Comment"
	# New
	::msgcat::mcset en_us "Add File (%s)" "Add File (%s)"
	# New
	::msgcat::mcset en_us "Add Item" "Add Item"
	# New
	::msgcat::mcset en_us "Add" "Add"
	# New
	::msgcat::mcset en_us "Adjust Font" "Adjust Font"
	# New
	::msgcat::mcset en_us "All" "All"
	# New
	::msgcat::mcset en_us "Allow modifications (must be single writer)" "Allow modifications (must be single writer)"
	# New
	::msgcat::mcset en_us "Apply" "Apply"
	# New
	::msgcat::mcset en_us "Are you sure you want to delete %s items?" "Are you sure you want to delete %s items?"
	# New
	::msgcat::mcset en_us "Are you sure you want to delete '%s' ?" "Are you sure you want to delete '%s' ?"
	# New
	::msgcat::mcset en_us "Are you sure you want to delete the Project (%s)?" "Are you sure you want to delete the Project (%s)?"
	# New
	::msgcat::mcset en_us "Are you sure you want to delete this item ?" "Are you sure you want to delete this item ?"
	# New
	::msgcat::mcset en_us "Are you sure you want to delete those items?" "Are you sure you want to delete those items?"
	# New
	::msgcat::mcset en_us "Are you sure, you want to close '%s' project ?" "Are you sure, you want to close '%s' project ?"
	# New
	::msgcat::mcset en_us "Arrange Project" "Arrange Project"
	# New
	::msgcat::mcset en_us "Asia" "Asia"
	# New
	::msgcat::mcset en_us "Auto Clear before Run Command" "Auto Clear before Run Command"
	# New
	::msgcat::mcset en_us "Automatic check on startup." "Automatic check on startup."
	# New
	::msgcat::mcset en_us "Bottom Frame" "Bottom Frame"
	# New
	::msgcat::mcset en_us "Browse" "Browse"
	# New
	::msgcat::mcset en_us "Browse..." "Browse..."
	# New
	::msgcat::mcset en_us "C Support" "C Support"
	# New
	::msgcat::mcset en_us "Can't change directory to %s" "Can't change directory to %s"
	# New
	::msgcat::mcset en_us "Can't connect to update server." "Can't connect to update server."
	# New
	::msgcat::mcset en_us "Cancel" "Cancel"
	# New
	::msgcat::mcset en_us "Case Sensitive" "Case Sensitive"
	# New
	::msgcat::mcset en_us "Change State" "Change State"
	# New
	::msgcat::mcset en_us "Check for updates..." "Check for updates..."
	# New
	::msgcat::mcset en_us "Check Syntax (Nagelfar)" "Check Syntax (Nagelfar)"
	# New
	::msgcat::mcset en_us "Check" "Check"
	# New
	::msgcat::mcset en_us "Checking for Updates ..." "Checking for Updates ..."
	# New
	::msgcat::mcset en_us "Choose  Font" "Choose  Font"
	# New
	::msgcat::mcset en_us "Choose %s Font" "Choose %s Font"
	# New
	::msgcat::mcset en_us "Choose A File" "Choose A File"
	# New
	::msgcat::mcset en_us "Choose A Project" "Choose A Project"
	# New
	::msgcat::mcset en_us "Choose Cursor" "Choose Cursor"
	# New
	::msgcat::mcset en_us "Choose Directory" "Choose Directory"
	# New
	::msgcat::mcset en_us "Choose Font" "Choose Font"
	# New
	::msgcat::mcset en_us "Choose Program" "Choose Program"
	# New
	::msgcat::mcset en_us "Clear All Marks" "Clear All Marks"
	# New
	::msgcat::mcset en_us "Clear All" "Clear All"
	# New
	::msgcat::mcset en_us "Clear" "Clear"
	# New
	::msgcat::mcset en_us "Close All" "Close All"
	# New
	::msgcat::mcset en_us "Close Project" "Close Project"
	# New
	::msgcat::mcset en_us "Close" "Close"
	# New
	::msgcat::mcset en_us "Code Outline" "Code Outline"
	# New
	::msgcat::mcset en_us "Coding Assistant" "Coding Assistant"
	# New
	::msgcat::mcset en_us "Collapse All" "Collapse All"
	# New
	::msgcat::mcset en_us "Color Picker" "Color Picker"
	# New
	::msgcat::mcset en_us "Command" "Command"
	# New
	::msgcat::mcset en_us "Command:" "Command:"
	# New
	::msgcat::mcset en_us "Console" "Console"
	# New
	::msgcat::mcset en_us "Copied %s" "Copied %s"
	# New
	::msgcat::mcset en_us "Copy '%s'" "Copy '%s'"
	# New
	::msgcat::mcset en_us "Copy Current Line" "Copy Current Line"
	# New
	::msgcat::mcset en_us "Copy" "Copy"
	# New
	::msgcat::mcset en_us "Copyright (C) 2009 - %s Yuan-Liang Tai" "Copyright (C) 2009 - %s Yuan-Liang Tai"
	# New
	::msgcat::mcset en_us "Ctrl++" "Ctrl++"
	# New
	::msgcat::mcset en_us "Ctrl+-" "Ctrl+-"
	# New
	::msgcat::mcset en_us "Ctrl+Left" "Ctrl+Left"
	# New
	::msgcat::mcset en_us "Ctrl+Right" "Ctrl+Right"
	# New
	::msgcat::mcset en_us "Ctrl+w" "Ctrl+w"
	# New
	::msgcat::mcset en_us "Cut %s" "Cut %s"
	# New
	::msgcat::mcset en_us "Cut Current Line" "Cut Current Line"
	# New
	::msgcat::mcset en_us "Cut" "Cut"
	# New
	::msgcat::mcset en_us "Decrease Line Indent" "Decrease Line Indent"
	# New
	::msgcat::mcset en_us "Default Encoding" "Default Encoding"
	# New
	::msgcat::mcset en_us "Default File Format" "Default File Format"
	# New
	::msgcat::mcset en_us "Delete Completed Items" "Delete Completed Items"
	# New
	::msgcat::mcset en_us "Delete" "Delete"
	# New
	::msgcat::mcset en_us "Descrease Size" "Descrease Size"
	# New
	::msgcat::mcset en_us "Description" "Description"
	# New
	::msgcat::mcset en_us "Details..." "Details..."
	# New
	::msgcat::mcset en_us "directory base name of file" "directory base name of file"
	# New
	::msgcat::mcset en_us "directory path of file" "directory path of file"
	# New
	::msgcat::mcset en_us "Directory:" "Directory:"
	# New
	::msgcat::mcset en_us "Do not compress files added to starkit" "Do not compress files added to starkit"
	# New
	::msgcat::mcset en_us "Do Not Save" "Do Not Save"
	# New
	::msgcat::mcset en_us "Done." "Done."
	# New
	::msgcat::mcset en_us "Download latest version of the %s ." "Download latest version of the %s ."
	# New
	::msgcat::mcset en_us "Eastern Europe" "Eastern Europe"
	# New
	::msgcat::mcset en_us "Edit" "Edit"
	# New
	::msgcat::mcset en_us "Editor" "Editor"
	# New
	::msgcat::mcset en_us "Empty Project" "Empty Project"
	# New
	::msgcat::mcset en_us "Encoding: %s" "Encoding: %s"
	# New
	::msgcat::mcset en_us "Error" "Error"
	# New
	::msgcat::mcset en_us "Existing File..." "Existing File..."
	# New
	::msgcat::mcset en_us "Exit" "Exit"
	# New
	::msgcat::mcset en_us "EzSDX" "EzSDX"
	# New
	::msgcat::mcset en_us "file base name" "file base name"
	# New
	::msgcat::mcset en_us "File name already exists." "File name already exists."
	# New
	::msgcat::mcset en_us "file path" "file path"
	# New
	::msgcat::mcset en_us "File" "File"
	# New
	::msgcat::mcset en_us "Filter:" "Filter:"
	# New
	::msgcat::mcset en_us "Find : " "Find : "
	# New
	::msgcat::mcset en_us "Find All" "Find All"
	# New
	::msgcat::mcset en_us "Find And Replace" "Find And Replace"
	# New
	::msgcat::mcset en_us "Find In Current Document" "Find In Current Document"
	# New
	::msgcat::mcset en_us "Find in files" "Find in files"
	# New
	::msgcat::mcset en_us "Find In Files..." "Find In Files..."
	# New
	::msgcat::mcset en_us "Find Next" "Find Next"
	# New
	::msgcat::mcset en_us "Find Previous" "Find Previous"
	# New
	::msgcat::mcset en_us "Find what:" "Find what:"
	# New
	::msgcat::mcset en_us "Find" "Find"
	# New
	::msgcat::mcset en_us "Find/Replace" "Find/Replace"
	# New
	::msgcat::mcset en_us "Find/Replace..." "Find/Replace..."
	# New
	::msgcat::mcset en_us "Finished" "Finished"
	# New
	::msgcat::mcset en_us "First Line" "First Line"
	# New
	::msgcat::mcset en_us "Folder" "Folder"
	# New
	::msgcat::mcset en_us "Font" "Font"
	# New
	::msgcat::mcset en_us "Format: %s" "Format: %s"
	# New
	::msgcat::mcset en_us "Goto Line..." "Goto Line..."
	# New
	::msgcat::mcset en_us "Goto" "Goto"
	# New
	::msgcat::mcset en_us "Help" "Help"
	# New
	::msgcat::mcset en_us "Hide Completed Items" "Hide Completed Items"
	# New
	::msgcat::mcset en_us "Hide" "Hide"
	# New
	::msgcat::mcset en_us "Highlight" "Highlight"
	# New
	::msgcat::mcset en_us "Hotkey:" "Hotkey:"
	# New
	::msgcat::mcset en_us "In Progress" "In Progress"
	# New
	::msgcat::mcset en_us "Include Runtime (Starpack)" "Include Runtime (Starpack)"
	# New
	::msgcat::mcset en_us "Increase Line Indent" "Increase Line Indent"
	# New
	::msgcat::mcset en_us "Increase Size" "Increase Size"
	# New
	::msgcat::mcset en_us "Information" "Information"
	# New
	::msgcat::mcset en_us "Jump to Matching Brace" "Jump to Matching Brace"
	# New
	::msgcat::mcset en_us "Keyword:" "Keyword:"
	# New
	::msgcat::mcset en_us "Kill Running Command" "Kill Running Command"
	# New
	::msgcat::mcset en_us "Languages" "Languages"
	# New
	::msgcat::mcset en_us "Large Font..." "Large Font..."
	# New
	::msgcat::mcset en_us "Last Line" "Last Line"
	# New
	::msgcat::mcset en_us "Left Frame" "Left Frame"
	# New
	::msgcat::mcset en_us "Left-Click : New File%sRight-Click : Show Menu" "Left-Click : New File%sRight-Click : Show Menu"
	# New
	::msgcat::mcset en_us "Left-Click : Open File...%sRight-Click : Show Menu" "Left-Click : Open File...%sRight-Click : Show Menu"
	# New
	::msgcat::mcset en_us "Left-Click : Run Last Command%sRight-Click : Show Menu" "Left-Click : Run Last Command%sRight-Click : Show Menu"
	# New
	::msgcat::mcset en_us "Line Numbers" "Line Numbers"
	# New
	::msgcat::mcset en_us "Line Operations" "Line Operations"
	# New
	::msgcat::mcset en_us "Line: %s   Column: %s" "Line: %s   Column: %s"
	# New
	::msgcat::mcset en_us "Line:" "Line:"
	# New
	::msgcat::mcset en_us "Lines: %s" "Lines: %s"
	# New
	::msgcat::mcset en_us "List All Pages" "List All Pages"
	# New
	::msgcat::mcset en_us "Make Active" "Make Active"
	# New
	::msgcat::mcset en_us "Marks" "Marks"
	# New
	::msgcat::mcset en_us "Match case" "Match case"
	# New
	::msgcat::mcset en_us "Menu Font..." "Menu Font..."
	# New
	::msgcat::mcset en_us "Message:" "Message:"
	# New
	::msgcat::mcset en_us "Middle East" "Middle East"
	# New
	::msgcat::mcset en_us "Middle Font..." "Middle Font..."
	# New
	::msgcat::mcset en_us "Move Backward" "Move Backward"
	# New
	::msgcat::mcset en_us "Move Down Current Line" "Move Down Current Line"
	# New
	::msgcat::mcset en_us "Move Down" "Move Down"
	# New
	::msgcat::mcset en_us "Move Forward" "Move Forward"
	# New
	::msgcat::mcset en_us "Move to Bottom Frame" "Move to Bottom Frame"
	# New
	::msgcat::mcset en_us "Move to Bottom" "Move to Bottom"
	# New
	::msgcat::mcset en_us "Move to Left Frame" "Move to Left Frame"
	# New
	::msgcat::mcset en_us "Move to Right Frame" "Move to Right Frame"
	# New
	::msgcat::mcset en_us "Move to Top" "Move to Top"
	# New
	::msgcat::mcset en_us "Move Up Current Line" "Move Up Current Line"
	# New
	::msgcat::mcset en_us "Move Up" "Move Up"
	# New
	::msgcat::mcset en_us "Multiline" "Multiline"
	# New
	::msgcat::mcset en_us "Nagelfar" "Nagelfar"
	# New
	::msgcat::mcset en_us "New File" "New File"
	# New
	::msgcat::mcset en_us "New Project - %s" "New Project - %s"
	# New
	::msgcat::mcset en_us "New Project" "New Project"
	# New
	::msgcat::mcset en_us "New Project..." "New Project..."
	# New
	::msgcat::mcset en_us "New" "New"
	# New
	::msgcat::mcset en_us "Next File" "Next File"
	# New
	::msgcat::mcset en_us "Next Mark" "Next Mark"
	# New
	::msgcat::mcset en_us "Next Page" "Next Page"
	# New
	::msgcat::mcset en_us "None" "None"
	# New
	::msgcat::mcset en_us "Not Started" "Not Started"
	# New
	::msgcat::mcset en_us "Notes" "Notes"
	# New
	::msgcat::mcset en_us "Ok" "Ok"
	# New
	::msgcat::mcset en_us "Open File" "Open File"
	# New
	::msgcat::mcset en_us "Open File..." "Open File..."
	# New
	::msgcat::mcset en_us "Open Project" "Open Project"
	# New
	::msgcat::mcset en_us "Open Project..." "Open Project..."
	# New
	::msgcat::mcset en_us "Options" "Options"
	# New
	::msgcat::mcset en_us "Outline" "Outline"
	# New
	::msgcat::mcset en_us "Output can't empty!!" "Output can't empty!!"
	# New
	::msgcat::mcset en_us "Output" "Output"
	# New
	::msgcat::mcset en_us "Panes" "Panes"
	# New
	::msgcat::mcset en_us "Paste As New Line" "Paste As New Line"
	# New
	::msgcat::mcset en_us "Paste" "Paste"
	# New
	::msgcat::mcset en_us "Pasted %s" "Pasted %s"
	# New
	::msgcat::mcset en_us "Please restart %s to apply settings." "Please restart %s to apply settings."
	# New
	::msgcat::mcset en_us "Please select the files you want to save" "Please select the files you want to save"
	# New
	::msgcat::mcset en_us "Plugins" "Plugins"
	# New
	::msgcat::mcset en_us "Preview" "Preview"
	# New
	::msgcat::mcset en_us "Previous File" "Previous File"
	# New
	::msgcat::mcset en_us "Previous Mark" "Previous Mark"
	# New
	::msgcat::mcset en_us "Previous Page" "Previous Page"
	# New
	::msgcat::mcset en_us "Project Name:" "Project Name:"
	# New
	::msgcat::mcset en_us "Project" "Project"
	# New
	::msgcat::mcset en_us "Project..." "Project..."
	# New
	::msgcat::mcset en_us "Projects" "Projects"
	# New
	::msgcat::mcset en_us "Question" "Question"
	# New
	::msgcat::mcset en_us "Quit" "Quit"
	# New
	::msgcat::mcset en_us "Ready" "Ready"
	# New
	::msgcat::mcset en_us "Recent Commands" "Recent Commands"
	# New
	::msgcat::mcset en_us "Recent Files" "Recent Files"
	# New
	::msgcat::mcset en_us "Recent Projects" "Recent Projects"
	# New
	::msgcat::mcset en_us "Redo" "Redo"
	# New
	::msgcat::mcset en_us "Refresh" "Refresh"
	# New
	::msgcat::mcset en_us "Regexp" "Regexp"
	# New
	::msgcat::mcset en_us "Regular Expression" "Regular Expression"
	# New
	::msgcat::mcset en_us "Remove Block Comment" "Remove Block Comment"
	# New
	::msgcat::mcset en_us "Rename" "Rename"
	# New
	::msgcat::mcset en_us "Rename:" "Rename:"
	# New
	::msgcat::mcset en_us "Replace All" "Replace All"
	# New
	::msgcat::mcset en_us "Replace what:" "Replace what:"
	# New
	::msgcat::mcset en_us "Replace" "Replace"
	# New
	::msgcat::mcset en_us "Reset" "Reset"
	# New
	::msgcat::mcset en_us "Right Frame" "Right Frame"
	# New
	::msgcat::mcset en_us "Run Command : %s" "Run Command : %s"
	# New
	::msgcat::mcset en_us "Run Command" "Run Command"
	# New
	::msgcat::mcset en_us "Run Command..." "Run Command..."
	# New
	::msgcat::mcset en_us "Run" "Run"
	# New
	::msgcat::mcset en_us "Run:" "Run:"
	# New
	::msgcat::mcset en_us "Save All Files" "Save All Files"
	# New
	::msgcat::mcset en_us "Save All" "Save All"
	# New
	::msgcat::mcset en_us "Save as ..." "Save as ..."
	# New
	::msgcat::mcset en_us "Save As..." "Save As..."
	# New
	::msgcat::mcset en_us "Save changee to %s ?" "Save changee to %s ?"
	# New
	::msgcat::mcset en_us "Save File" "Save File"
	# New
	::msgcat::mcset en_us "Save To?" "Save To?"
	# New
	::msgcat::mcset en_us "Save" "Save"
	# New
	::msgcat::mcset en_us "SDX" "SDX"
	# New
	::msgcat::mcset en_us "Search directory not valid!" "Search directory not valid!"
	# New
	::msgcat::mcset en_us "Search hidden files & folders" "Search hidden files & folders"
	# New
	::msgcat::mcset en_us "Select All" "Select All"
	# New
	::msgcat::mcset en_us "Select to Matching Brace" "Select to Matching Brace"
	# New
	::msgcat::mcset en_us "Small Font..." "Small Font..."
	# New
	::msgcat::mcset en_us "Sort Projects" "Sort Projects"
	# New
	::msgcat::mcset en_us "Sort Symbol" "Sort Symbol"
	# New
	::msgcat::mcset en_us "Start in:" "Start in:"
	# New
	::msgcat::mcset en_us "Start" "Start"
	# New
	::msgcat::mcset en_us "State" "State"
	# New
	::msgcat::mcset en_us "Stop" "Stop"
	# New
	::msgcat::mcset en_us "Successed!!" "Successed!!"
	# New
	::msgcat::mcset en_us "Syntax Highlighting" "Syntax Highlighting"
	# New
	::msgcat::mcset en_us "Syntax Hint" "Syntax Hint"
	# New
	::msgcat::mcset en_us "Tab Width" "Tab Width"
	# New
	::msgcat::mcset en_us "Tcl Project" "Tcl Project"
	# New
	::msgcat::mcset en_us "Tcl Script" "Tcl Script"
	# New
	::msgcat::mcset en_us "Tcl Support" "Tcl Support"
	# New
	::msgcat::mcset en_us "Tclkit" "Tclkit"
	# New
	::msgcat::mcset en_us "Templates:" "Templates:"
	# New
	::msgcat::mcset en_us "Text File" "Text File"
	# New
	::msgcat::mcset en_us "The '%s' already delete from the filesystem." "The '%s' already delete from the filesystem."
	# New
	::msgcat::mcset en_us "The '%s' already exists in the directory. What do you want to do?" "The '%s' already exists in the directory. What do you want to do?"
	# New
	::msgcat::mcset en_us "The '%s' already exists in the directory." "The '%s' already exists in the directory."
	# New
	::msgcat::mcset en_us "The operation will reload this file. Save it ?" "The operation will reload this file. Save it ?"
	# New
	::msgcat::mcset en_us "The pattern was not found." "The pattern was not found."
	# New
	::msgcat::mcset en_us "Themes" "Themes"
	# New
	::msgcat::mcset en_us "These are no new updates available." "These are no new updates available."
	# New
	::msgcat::mcset en_us "These is new %s available!!" "These is new %s available!!"
	# New
	::msgcat::mcset en_us "Time" "Time"
	# New
	::msgcat::mcset en_us "Toggle Mark" "Toggle Mark"
	# New
	::msgcat::mcset en_us "Tools" "Tools"
	# New
	::msgcat::mcset en_us "Trim Trailing Space" "Trim Trailing Space"
	# New
	::msgcat::mcset en_us "Undo" "Undo"
	# New
	::msgcat::mcset en_us "User Interface" "User Interface"
	# New
	::msgcat::mcset en_us "Version %s changelog : " "Version %s changelog : "
	# New
	::msgcat::mcset en_us "View Line Numbers" "View Line Numbers"
	# New
	::msgcat::mcset en_us "View" "View"
	# New
	::msgcat::mcset en_us "Warning" "Warning"
	# New
	::msgcat::mcset en_us "Warring" "Warring"
	# New
	::msgcat::mcset en_us "Web Site" "Web Site"
	# New
	::msgcat::mcset en_us "Web Site: %s" "Web Site: %s"
	# New
	::msgcat::mcset en_us "Western Europe" "Western Europe"
	# New
	::msgcat::mcset en_us "Where is your SDX?" "Where is your SDX?"
	# New
	::msgcat::mcset en_us "Where is your Tclkit?" "Where is your Tclkit?"
	# New
	::msgcat::mcset en_us "Window" "Window"
	# New
	::msgcat::mcset en_us "Workspace:" "Workspace:"
	# New
	::msgcat::mcset en_us "Wrap File" "Wrap File"
	# New
	::msgcat::mcset en_us "Wrap Project" "Wrap Project"

}
