# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded twidget::base 1.0 [list source [file join $dir base.tcl]]
package ifneeded twidget::ibox 1.0 [list source [file join $dir ibox.tcl]]
package ifneeded twidget::rc 1.0 [list source [file join $dir rc.tcl]]
package ifneeded twidget::hook 1.0 [list source [file join $dir hook.tcl]]
package ifneeded twidget::dialog 1.0 [list source [file join $dir dialog.tcl]]
package ifneeded twidget::toolbar 1.0 [list source [file join $dir toolbar.tcl]]

package ifneeded twidget::editor 1.0 [list source [file join $dir editor.tcl]]
package ifneeded twidget::notebook 1.0 [list source [file join $dir notebook.tcl]]
package ifneeded twidget::treeview 1.0 [list source [file join $dir treeview.tcl]]

