# This file is automatically generated and will be overwritten
namespace eval twapi {
    variable dll_base_name twapi
}
# The build_id is generated automatically on every build
set twapi::build_id 91d23aee-15b2-45c6-4566-269b25f18283
